/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface CanvasRecorder {}
  interface SlitScan {
    'camera': string;
    'mode': string;
    'slices': number;
  }
  interface TemporalisApp {}
}

declare global {


  interface HTMLCanvasRecorderElement extends Components.CanvasRecorder, HTMLStencilElement {}
  var HTMLCanvasRecorderElement: {
    prototype: HTMLCanvasRecorderElement;
    new (): HTMLCanvasRecorderElement;
  };

  interface HTMLSlitScanElement extends Components.SlitScan, HTMLStencilElement {}
  var HTMLSlitScanElement: {
    prototype: HTMLSlitScanElement;
    new (): HTMLSlitScanElement;
  };

  interface HTMLTemporalisAppElement extends Components.TemporalisApp, HTMLStencilElement {}
  var HTMLTemporalisAppElement: {
    prototype: HTMLTemporalisAppElement;
    new (): HTMLTemporalisAppElement;
  };
  interface HTMLElementTagNameMap {
    'canvas-recorder': HTMLCanvasRecorderElement;
    'slit-scan': HTMLSlitScanElement;
    'temporalis-app': HTMLTemporalisAppElement;
  }
}

declare namespace LocalJSX {
  interface CanvasRecorder {}
  interface SlitScan {
    'camera'?: string;
    'mode'?: string;
    'slices'?: number;
  }
  interface TemporalisApp {}

  interface IntrinsicElements {
    'canvas-recorder': CanvasRecorder;
    'slit-scan': SlitScan;
    'temporalis-app': TemporalisApp;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'canvas-recorder': LocalJSX.CanvasRecorder & JSXBase.HTMLAttributes<HTMLCanvasRecorderElement>;
      'slit-scan': LocalJSX.SlitScan & JSXBase.HTMLAttributes<HTMLSlitScanElement>;
      'temporalis-app': LocalJSX.TemporalisApp & JSXBase.HTMLAttributes<HTMLTemporalisAppElement>;
    }
  }
}


